package net.TelepathicGrunt.UltraAmplified.World.Generation;

import java.lang.reflect.Type;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;

import net.minecraft.init.Biomes;
import net.minecraft.util.JsonUtils;
import net.minecraft.world.biome.Biome;

public class ChunkGeneratorSettingsUA {
	 public final float coordinateScale;
    public final float heightScale;
    public final float upperLimitScale;
    public final float lowerLimitScale;
    public final float depthNoiseScaleX;
    public final float depthNoiseScaleZ;
    public final float depthNoiseScaleExponent;
    public final float mainNoiseScaleX;
    public final float mainNoiseScaleY;
    public final float mainNoiseScaleZ;
    public final float baseSize;
    public final float stretchY;
    public final float biomeDepthWeight;
    public final float biomeDepthOffset;
    public final float biomeScaleWeight;
    public final float biomeScaleOffset;
    public final int seaLevel;
    public final boolean useCaves;
    public final boolean useDungeons;
    public final int dungeonChance;
    public final boolean useStrongholds;
    public final boolean useVillages;
    public final boolean useMineShafts;
    public final boolean useTemples;
    public final boolean useMonuments;
    public final boolean useMansion;
    public final boolean useRavines;
    public final boolean useWaterLakes;
    public final int waterLakeChance;
    public final boolean useLavaLakes;
    public final int lavaLakeChance;
    public final boolean useLavaOceans;
    public final int fixedBiome;
    public final int biomeSize;
    public final int riverSize;
    public final int dirtSize;
    public final int dirtCount;
    public final int dirtMinHeight;
    public final int dirtMaxHeight;
    public final int gravelSize;
    public final int gravelCount;
    public final int gravelMinHeight;
    public final int gravelMaxHeight;
    public final int graniteSize;
    public final int graniteCount;
    public final int graniteMinHeight;
    public final int graniteMaxHeight;
    public final int dioriteSize;
    public final int dioriteCount;
    public final int dioriteMinHeight;
    public final int dioriteMaxHeight;
    public final int andesiteSize;
    public final int andesiteCount;
    public final int andesiteMinHeight;
    public final int andesiteMaxHeight;
    public final int coalSize;
    public final int coalCount;
    public final int coalMinHeight;
    public final int coalMaxHeight;
    public final int ironSize;
    public final int ironCount;
    public final int ironMinHeight;
    public final int ironMaxHeight;
    public final int goldSize;
    public final int goldCount;
    public final int goldMinHeight;
    public final int goldMaxHeight;
    public final int redstoneSize;
    public final int redstoneCount;
    public final int redstoneMinHeight;
    public final int redstoneMaxHeight;
    public final int diamondSize;
    public final int diamondCount;
    public final int diamondMinHeight;
    public final int diamondMaxHeight;
    public final int lapisSize;
    public final int lapisCount;
    public final int lapisCenterHeight;
    public final int lapisSpread;

    public ChunkGeneratorSettingsUA()
    {
    	this.coordinateScale = 684.412F;
        this.heightScale = 684.412F;
        this.upperLimitScale = 512.0F;
        this.lowerLimitScale = 512.0F;
        this.depthNoiseScaleX = 200.0F;
        this.depthNoiseScaleZ = 200.0F;
        this.depthNoiseScaleExponent = 0.5F;
        this.mainNoiseScaleX = 80.0F;
        this.mainNoiseScaleY = 160.0F;
        this.mainNoiseScaleZ = 80.0F;
        this.baseSize = 8.5F;
        this.stretchY = 12.0F;
        this.biomeDepthWeight = 1.0F;
        this.biomeDepthOffset = 0.0F;
        this.biomeScaleWeight = 1.0F;
        this.biomeScaleOffset = 0.0F;
        this.seaLevel = 75;
        this.useCaves = true;
        this.useDungeons = true;
        this.dungeonChance = 8;
        this.useStrongholds = true;
        this.useVillages = true;
        this.useMineShafts = true;
        this.useTemples = true;
        this.useMonuments = true;
        this.useMansion = true;
        this.useRavines = true;
        this.useWaterLakes = true;
        this.waterLakeChance = 4;
        this.useLavaLakes = true;
        this.lavaLakeChance = 80;
        this.useLavaOceans = false;
        this.fixedBiome = -1;
        this.biomeSize = 4;
        this.riverSize = 4;
        this.dirtSize = 33;
        this.dirtCount = 10;
        this.dirtMinHeight = 0;
        this.dirtMaxHeight = 175;
        this.gravelSize = 33;
        this.gravelCount = 8;
        this.gravelMinHeight = 0;
        this.gravelMaxHeight = 256;
        this.graniteSize = 33;
        this.graniteCount = 17;
        this.graniteMinHeight = 0;
        this.graniteMaxHeight = 100;
        this.dioriteSize = 33;
        this.dioriteCount = 14;
        this.dioriteMinHeight = 0;
        this.dioriteMaxHeight = 150;
        this.andesiteSize = 33;
        this.andesiteCount = 20;
        this.andesiteMinHeight = 0;
        this.andesiteMaxHeight = 200;
        this.coalSize = 17;
        this.coalCount = 35;
        this.coalMinHeight = 0;
        this.coalMaxHeight = 240;
        this.ironSize = 9;
        this.ironCount = 50;
        this.ironMinHeight = 0;
        this.ironMaxHeight = 200;
        this.goldSize = 9;
        this.goldCount = 2;
        this.goldMinHeight = 0;
        this.goldMaxHeight = 50;
        this.redstoneSize = 8;
        this.redstoneCount = 12;
        this.redstoneMinHeight = 0;
        this.redstoneMaxHeight = 25;
        this.diamondSize = 8;
        this.diamondCount = 1;
        this.diamondMinHeight = 0;
        this.diamondMaxHeight = 25;
        this.lapisSize = 7;
        this.lapisCount = 2;
        this.lapisCenterHeight = 20;
        this.lapisSpread = 20;
    }
}
