package net.TelepathicGrunt.UltraAmplified.World.Generation;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import jline.internal.Log;
import net.TelepathicGrunt.UltraAmplified.Config.UAConfig;
import net.TelepathicGrunt.UltraAmplified.World.Biome.BiomeInit;
import net.minecraft.init.Biomes;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.gen.layer.GenLayer;
import net.minecraft.world.gen.layer.IntCache;

public class GenLayerHillsAndAmplifiedUA extends GenLayer
{
	/*
	 * This class generates M variants and Hills variants of biomes if they exist for that biome
	 */
	
	
    private static final Logger LOGGER = LogManager.getLogger();
    private final GenLayer riverLayer;
    private ChunkGeneratorSettingsUA settings;

    public GenLayerHillsAndAmplifiedUA(long p_i45479_1_, GenLayer p_i45479_3_, GenLayer p_i45479_4_, ChunkGeneratorSettingsUA settings)
    {
        super(p_i45479_1_);
        this.parent = p_i45479_3_;
        this.riverLayer = p_i45479_4_;
        this.settings = settings;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or Biome ID's based on the particular GenLayer subclass.
     */
    public int[] getInts(int areaX, int areaY, int areaWidth, int areaHeight)
    {
        int[] aint = this.parent.getInts(areaX - 1, areaY - 1, areaWidth + 2, areaHeight + 2);
        int[] aint1 = this.riverLayer.getInts(areaX - 1, areaY - 1, areaWidth + 2, areaHeight + 2);
        int[] aint2 = IntCache.getIntCache(areaWidth * areaHeight);

        for (int i = 0; i < areaHeight; ++i)
        {
            for (int j = 0; j < areaWidth; ++j)
            {
                this.initChunkSeed((long)(j + areaX), (long)(i + areaY));
                int k = aint[j + 1 + (i + 1) * (areaWidth + 2)];
                int l = aint1[j + 1 + (i + 1) * (areaWidth + 2)];
                Biome biome = Biome.getBiomeForId(k);
                boolean flag1 = biome != null && biome.isMutation();
                
                //This determines how common M variants and Hills are.
                //M variant happens if remander is between 1 and whatever number user picks for mutatedBiomeSpawnrate config.
                //Hills happen if remander is not 0 and the random number(0-2) equals 0.
                int remander = (l - 2) % 29;
                boolean flag = remander == 0;


                if ((UAConfig.biomeOptions.mutatedBiomeSpawnrate == 29 || (k != 0 && l >= 2 && remander >= 1 && remander <= UAConfig.biomeOptions.mutatedBiomeSpawnrate - 1)) && !flag1)
                {
                	//generates M variants
                    Biome biome3 = BiomeInit.getMutationForBiome(biome);
                    aint2[j + i * areaWidth] = biome3 == null ? k : Biome.getIdForBiome(biome3);
                }
                else if (this.nextInt(3) != 0 && !flag)
                {
                	//generates normal biome
                    aint2[j + i * areaWidth] = k;
                }
                else
                {
                	//generates hills
                    Biome biome1 = biome;

                    if (biome == BiomeInit.BiomeDesert)
                    {
                        biome1 = BiomeInit.BiomeDesertHills;
                    }
                    else if (biome == BiomeInit.BiomeForest)
                    {
                        biome1 = BiomeInit.BiomeForestHills;
                    }
                    else if (biome == BiomeInit.BiomeBirchForest)
                    {
                        biome1 = BiomeInit.BiomeBirchForestHills;
                    }
                    else if (biome == BiomeInit.BiomeRoofedForest && settings.plains)
                    {
                    	//makes sure plains is selected in the config setting before allowing it to spawn through here
                        biome1 = BiomeInit.BiomePlains;
                    }
                    else if (biome == BiomeInit.BiomeTaiga)
                    {
                        biome1 = BiomeInit.BiomeTaigaHills;
                    }
                    else if (biome == BiomeInit.BiomeRedwoodTaiga)
                    {
                        biome1 = BiomeInit.BiomeRedwoodTaigaHills;
                    }
                    else if (biome == BiomeInit.BiomeColdTaiga)
                    {
                        biome1 = BiomeInit.BiomeColdTaigaHills;
                    }
                    else if (biome == BiomeInit.BiomePlains && settings.forest)
                    {
                    	//makes sure forest is selected in the config setting before allowing it to spawn through here
                        if (this.nextInt(3) == 0)
                        {
                            biome1 = BiomeInit.BiomeForestHills;
                        }
                        else
                        {
                            biome1 = BiomeInit.BiomeForest;
                        }
                    }
                    else if (biome == BiomeInit.BiomeIceFlats && settings.iceMountain)
                    {
                    	//makes sure ice mountain is selected in the config setting before allowing it to spawn through here
                        biome1 = BiomeInit.BiomeIceMountain;
                    }
                    else if (biome == BiomeInit.BiomeJungle)
                    {
                        biome1 = BiomeInit.BiomeJungleHills;
                    }
                    else if (biome == BiomeInit.BiomeExtremeHills)
                    {
                        biome1 = BiomeInit.BiomeExtremeHillsPlus;
                    }
                    else if (biome == BiomeInit.BiomeSavanna)
                    {
                        biome1 = BiomeInit.BiomeSavannaRock;
                    }
                    else if (biomesEqualOrMesaPlateau(k, Biome.getIdForBiome(BiomeInit.BiomeMesaRock)))
                    {
                        biome1 = BiomeInit.BiomeMesa;
                    }

                    int j2 = Biome.getIdForBiome(biome1);

                    if (flag && j2 != k)
                    {
                        Biome biome2 = Biome.getMutationForBiome(biome1);
                        j2 = biome2 == null ? k : Biome.getIdForBiome(biome2);
                    }

                    if (j2 == k)
                    {
                        aint2[j + i * areaWidth] = k;
                    }
                    else
                    {
                        int k2 = aint[j + 1 + (i + 0) * (areaWidth + 2)];
                        int j1 = aint[j + 2 + (i + 1) * (areaWidth + 2)];
                        int k1 = aint[j + 0 + (i + 1) * (areaWidth + 2)];
                        int l1 = aint[j + 1 + (i + 2) * (areaWidth + 2)];
                        int i2 = 0;

                        if (biomesEqualOrMesaPlateau2(k2, k))
                        {
                            ++i2;
                        }

                        if (biomesEqualOrMesaPlateau2(j1, k))
                        {
                            ++i2;
                        }

                        if (biomesEqualOrMesaPlateau2(k1, k))
                        {
                            ++i2;
                        }

                        if (biomesEqualOrMesaPlateau2(l1, k))
                        {
                            ++i2;
                        }

                        if (i2 >= 3)
                        {
                            aint2[j + i * areaWidth] = j2;
                        }
                        else
                        {
                            aint2[j + i * areaWidth] = k;
                        }
                    }
                }
            }
        }

        return aint2;
    }
    
    
    //voodoo stuff. idk.
    protected static boolean biomesEqualOrMesaPlateau2(int biomeIDA, int biomeIDB)
    {
        if (biomeIDA == biomeIDB)
        {
            return true;
        }
        else
        {
            Biome biome = Biome.getBiome(biomeIDA);
            Biome biome1 = Biome.getBiome(biomeIDB);

            if (biome != null && biome1 != null)
            {
                if (biome != BiomeInit.BiomeMesaRock && biome != BiomeInit.BiomeMesaClearRock)
                {
                    return biome == biome1 || biome.getBiomeClass() == biome1.getBiomeClass();
                }
                else
                {
                    return biome1 == BiomeInit.BiomeMesaRock || biome1 == BiomeInit.BiomeMesaClearRock;
                }
            }
            else
            {
                return false;
            }
        }
    }
}