modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)

[[mods]] #mandatory
modId="ultra_amplified_mod" #mandatory
version="0.5.0" #mandatory
displayName="Ultra Amplified Mod" #mandatory
displayURL="https://minecraft.curseforge.com/projects/ultra-amplified-mod"
logoFile="assets/ultra_amplified_mod/textures/ultra_amplified_logo.png"
credits="Thanks to all the Forge tutorials and debugging help from other modders to help make this mod possible!"
# The description text for the mod (multi line!) (#mandatory)
description='''
A world beyond amplified world type! Discover incredible landscape! Loot filled structures! And many boosted Biomes along with the End and Nether in the Overworld!
'''

[[dependencies.testmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[25,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"