modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory
license="https://github.com/TelepathicGrunt/WorldBlender/blob/master/LICENSE"

[[mods]] #mandatory
modId="ultra_amplified_dimension" #mandatory
logoFile="ultraamplifiedlogo.png"
logoBlur=false
version="${version}" #mandatory
displayName="Ultra Amplified Dimension" #mandatory
displayURL="https://minecraft.curseforge.com/projects/ultra-amplified-mod"
authors="TelepathicGrunt"
credits="special thanks to all the Forge tutorials and debugging help from other modders to help make this mod possible!"
# The description text for the mod (multi line!) (#mandatory)
description='''A dimension that is more insane than amplified world type! Discover incredible landscape! Loot filled structures! And many boosted Biomes along with the End and Nether in the dimension!'''

[[dependencies.ultra_amplified_dimension]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4, 1.17.0)"

[[dependencies.ultra_amplified_dimension]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35.1.36,)" #mandatory
    ordering="NONE"
    side="BOTH"