# Find more information on toml format here:?  https://github.com/toml-lang/toml???
modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory

[[mods]] #mandatory
modId="ultra_amplified_mod" #mandatory
logoFile="ultraamplifiedlogo.png"
version="0.6.8" #mandatory
displayName="Ultra Amplified Mod" #mandatory
displayURL="https://minecraft.curseforge.com/projects/ultra-amplified-mod"
authors="TelepathicGrunt"
credits="special thanks to all the Forge tutorials and debugging help from other modders to help make this mod possible!"
# The description text for the mod (multi line!) (#mandatory)
description='''A world beyond amplified world type! Discover incredible landscape! Loot filled structures! And many boosted Biomes along with the End and Nether in the Overworld!'''