package net.telepathicgrunt.ultraamplified.world.feature.structure;

import net.minecraft.world.gen.feature.structure.IStructurePieceType;
import net.telepathicgrunt.ultraamplified.world.dimension.RegUtil;


public class StructureInitUA
{

	public static IStructurePieceType TEDPUA;
	public static IStructurePieceType ECPUA;
	public static IStructurePieceType ISTUA;
	public static IStructurePieceType IGLUUA;
	public static IStructurePieceType TEJPUA;
	public static IStructurePieceType MSCORRIDORUA;
	public static IStructurePieceType MSCROSSINGUA;
	public static IStructurePieceType MSROOMUA;
	public static IStructurePieceType MSSTAIRSUA;
	public static IStructurePieceType MTUA;
	public static IStructurePieceType ORPUA;
	public static IStructurePieceType SHIPWRECKUA;
	public static IStructurePieceType TESHUA;
	public static IStructurePieceType NEBCRUA;
	public static IStructurePieceType NEBEFUA;
	public static IStructurePieceType NEBSUA;
	public static IStructurePieceType NECCSUA;
	public static IStructurePieceType NECTBUA;
	public static IStructurePieceType NECEUA;
	public static IStructurePieceType NESCSCUA;
	public static IStructurePieceType NESCLTUA;
	public static IStructurePieceType NESCUA;
	public static IStructurePieceType NESCRTUA;
	public static IStructurePieceType NECSRUA;
	public static IStructurePieceType NEMTUA;
	public static IStructurePieceType NERCUA;
	public static IStructurePieceType NESRUA;
	public static IStructurePieceType NESTARTUA;
	public static IStructurePieceType OMBUA;
	public static IStructurePieceType OMCRUA;
	public static IStructurePieceType OMDXRUA;
	public static IStructurePieceType OMDXYRUA;
	public static IStructurePieceType OMDYRUA;
	public static IStructurePieceType OMDYZRUA;
	public static IStructurePieceType OMDZRUA;
	public static IStructurePieceType OMENTRYUA;
	public static IStructurePieceType OMPENTHOUSEUA;
	public static IStructurePieceType OMSIMPLEUA;
	public static IStructurePieceType OMSIMPLETUA;
	public static IStructurePieceType OMWRUA;
	public static IStructurePieceType SHCCUA;
	public static IStructurePieceType SHFCUA;
	public static IStructurePieceType SH5CUA;
	public static IStructurePieceType SHLTUA;
	public static IStructurePieceType SHLIUA;
	public static IStructurePieceType SHPRUA;
	public static IStructurePieceType SHPHUA;
	public static IStructurePieceType SHRTUA;
	public static IStructurePieceType SHRCUA;
	public static IStructurePieceType SHSDUA;
	public static IStructurePieceType SHSTARTUA;
	public static IStructurePieceType SHSUA;
	public static IStructurePieceType SHSSDUA;
	public static IStructurePieceType VISTUA;
	public static IStructurePieceType VIDFUA;
	public static IStructurePieceType VIFUA;
	public static IStructurePieceType VIPHUA;
	public static IStructurePieceType VIBHUA;
	public static IStructurePieceType VISUA;
	public static IStructurePieceType VITRHUA;
	public static IStructurePieceType VISHUA;
	public static IStructurePieceType VISRUA;
	public static IStructurePieceType VIWUA;
	public static IStructurePieceType VISMHUA;
	public static IStructurePieceType VILUA;
	public static IStructurePieceType VISTARTUA;


	public static void registerStructurePieces()
	{
		TEDPUA = RegUtil.register(DesertTemplePiecesUA::new, "TeDPUA");
		ECPUA = RegUtil.register(EndCityPiecesUA.CityTemplate::new, "ECPUA");
		ISTUA = RegUtil.register(IceSpikeTemplePiecesUA.Piece::new, "ISTUA");
		IGLUUA = RegUtil.register(IglooPiecesUA.Piece::new, "IgluUA");
		TEJPUA = RegUtil.register(JungleTemplePiecesUA::new, "TeJPUA");
		MSCORRIDORUA = RegUtil.register(MineshaftPiecesUA.Corridor::new, "MSCorridorUA");
		MSCROSSINGUA = RegUtil.register(MineshaftPiecesUA.Cross::new, "MSCrossingUA");
		MSROOMUA = RegUtil.register(MineshaftPiecesUA.Room::new, "MSRoomUA");
		MSSTAIRSUA = RegUtil.register(MineshaftPiecesUA.Stairs::new, "MSStairsUA");
		MTUA = RegUtil.register(MushroomTemplePiecesUA.Piece::new, "MTUA");
		ORPUA = RegUtil.register(OceanRuinsPiecesUA.Piece::new, "ORPUA");
		SHIPWRECKUA = RegUtil.register(ShipwreckPiecesUA.Piece::new, "ShipwreckUA");
		TESHUA = RegUtil.register(WitchHutPiecesUA::new, "TeSHUA");
		NEBCRUA = RegUtil.register(FortressPiecesUA.Crossing3::new, "NeBCrUA");
		NEBEFUA = RegUtil.register(FortressPiecesUA.End::new, "NeBEFUA");
		NEBSUA = RegUtil.register(FortressPiecesUA.Straight::new, "NeBSUA");
		NECCSUA = RegUtil.register(FortressPiecesUA.Corridor3::new, "NeCCSUA");
		NECTBUA = RegUtil.register(FortressPiecesUA.Corridor4::new, "NeCTBUA");
		NECEUA = RegUtil.register(FortressPiecesUA.Entrance::new, "NeCEUA");
		NESCSCUA = RegUtil.register(FortressPiecesUA.Crossing2::new, "NeSCSCUA");
		NESCLTUA = RegUtil.register(FortressPiecesUA.Corridor::new, "NeSCLTUA");
		NESCUA = RegUtil.register(FortressPiecesUA.Corridor5::new, "NeSCUA");
		NESCRTUA = RegUtil.register(FortressPiecesUA.Corridor2::new, "NeSCRTUA");
		NECSRUA = RegUtil.register(FortressPiecesUA.NetherStalkRoom::new, "NeCSRUA");
		NEMTUA = RegUtil.register(FortressPiecesUA.Throne::new, "NeMTUA");
		NERCUA = RegUtil.register(FortressPiecesUA.Crossing::new, "NeRCUA");
		NESRUA = RegUtil.register(FortressPiecesUA.Stairs::new, "NeSRUA");
		NESTARTUA = RegUtil.register(FortressPiecesUA.Start::new, "NeStartUA");
		OMBUA = RegUtil.register(OceanMonumentPiecesUA.MonumentBuilding::new, "OMBUA");
		OMCRUA = RegUtil.register(OceanMonumentPiecesUA.MonumentCoreRoom::new, "OMCRUA");
		OMDXRUA = RegUtil.register(OceanMonumentPiecesUA.DoubleXRoom::new, "OMDXRUA");
		OMDXYRUA = RegUtil.register(OceanMonumentPiecesUA.DoubleXYRoom::new, "OMDXYRUA");
		OMDYRUA = RegUtil.register(OceanMonumentPiecesUA.DoubleYRoom::new, "OMDYRUA");
		OMDYZRUA = RegUtil.register(OceanMonumentPiecesUA.DoubleYZRoom::new, "OMDYZRUA");
		OMDZRUA = RegUtil.register(OceanMonumentPiecesUA.DoubleZRoom::new, "OMDZRUA");
		OMENTRYUA = RegUtil.register(OceanMonumentPiecesUA.EntryRoom::new, "OMEntryUA");
		OMPENTHOUSEUA = RegUtil.register(OceanMonumentPiecesUA.Penthouse::new, "OMPenthouseUA");
		OMSIMPLEUA = RegUtil.register(OceanMonumentPiecesUA.SimpleRoom::new, "OMSimpleUA");
		OMSIMPLETUA = RegUtil.register(OceanMonumentPiecesUA.SimpleTopRoom::new, "OMSimpleTUA");
		OMWRUA = RegUtil.register(OceanMonumentPiecesUA.WingRoom::new, "OMWRUA");
		SHCCUA = RegUtil.register(StrongholdPiecesUA.ChestCorridor::new, "SHCCUA");
		SHFCUA = RegUtil.register(StrongholdPiecesUA.Corridor::new, "SHFCUA");
		SH5CUA = RegUtil.register(StrongholdPiecesUA.Crossing::new, "SH5CUA");
		SHLTUA = RegUtil.register(StrongholdPiecesUA.LeftTurn::new, "SHLTUA");
		SHLIUA = RegUtil.register(StrongholdPiecesUA.Library::new, "SHLiUA");
		SHPRUA = RegUtil.register(StrongholdPiecesUA.PortalRoom::new, "SHPRUA");
		SHPHUA = RegUtil.register(StrongholdPiecesUA.Prison::new, "SHPHUA");
		SHRTUA = RegUtil.register(StrongholdPiecesUA.RightTurn::new, "SHRTUA");
		SHRCUA = RegUtil.register(StrongholdPiecesUA.RoomCrossing::new, "SHRCUA");
		SHSDUA = RegUtil.register(StrongholdPiecesUA.Stairs::new, "SHSDUA");
		SHSTARTUA = RegUtil.register(StrongholdPiecesUA.Stairs2::new, "SHStartUA");
		SHSUA = RegUtil.register(StrongholdPiecesUA.Straight::new, "SHSUA");
		SHSSDUA = RegUtil.register(StrongholdPiecesUA.StairsStraight::new, "SHSSDUA");
		VISTUA = RegUtil.register(VillagePastStyledPiecesUA.Church::new, "ViSTUA");
		VIDFUA = RegUtil.register(VillagePastStyledPiecesUA.Field1::new, "ViDFUA");
		VIFUA = RegUtil.register(VillagePastStyledPiecesUA.Field2::new, "ViFUA");
		VIPHUA = RegUtil.register(VillagePastStyledPiecesUA.WorkHouse::new, "ViPHUA");
		VIBHUA = RegUtil.register(VillagePastStyledPiecesUA.LibraryHouse::new, "ViBHUA");
		VISUA = RegUtil.register(VillagePastStyledPiecesUA.Blacksmith::new, "ViSUA");
		VITRHUA = RegUtil.register(VillagePastStyledPiecesUA.LargeHouse::new, "ViTRHUA");
		VISHUA = RegUtil.register(VillagePastStyledPiecesUA.FlatTopTinyHouse::new, "ViSHUA");
		VISRUA = RegUtil.register(VillagePastStyledPiecesUA.Path::new, "ViSRUA");
		VIWUA = RegUtil.register(VillagePastStyledPiecesUA.Well::new, "ViWUA");
		VISMHUA = RegUtil.register(VillagePastStyledPiecesUA.TinyHouse::new, "ViSmHUA");
		VILUA = RegUtil.register(VillagePastStyledPiecesUA.Torch::new, "ViLUA");
		VISTARTUA = RegUtil.register(VillagePastStyledPiecesUA.Start::new, "ViStartUA");
	}

}
